
  # Database
  db.driver: org.h2.Driver
  db.url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
  db.username: admin
  db.password: admin

  # Hibernate
  hibernate.dialect: org.hibernate.dialect.H2Dialect
  hibernate.show_sql: true
  hibernate.format_sql: true
  hibernate.hbm2ddl.auto: create
  entitymanager.packagesToScan: com.hrm.test.business

  # Spring
  spring:
    h2:
      console:
        enabled: true
    jpa:
      open-in-view: false

